//This root macro analyzes the Triton simulation results
//It processes the output files generated by the Triton simulation and extracts relevant data for analysis

int TritonAnalysis()
{


  // Create a TFile to read the output data
  TFile* inputFile = TFile::Open("RootFiles/Tritium710000.root", "READ");
  if (!inputFile || inputFile->IsZombie()) {
    std::cerr << "Error opening file!" << std::endl;
    return -1;
  }

  // Access the tree containing the simulation data
  TTree* tree = (TTree*)inputFile->Get("Tritium breeder");
  if (!tree) {
    std::cerr << "Error accessing tree!" << std::endl;
    return -1;
  }

  // Set up variables to hold data from the tree
  Double_t energyDep, PID, SourceEnergy;
  tree->SetBranchAddress("EabsTOT", &energyDep);
  tree->SetBranchAddress("PID", &PID);
  tree->SetBranchAddress("SourceEN", &SourceEnergy);

auto* hEabsTot = new TH1D("hEabsTOT", "Total Absorbed Energy", 1000, 0, 6); // Adjust binning as needed
auto* hSourceEnergy = new TH1D("hSourceEnergy", "Source Energy Distribution", 600, 0, 20); // Adjust binning as needed
  
  // Loop over entries in the tree and perform analysis
  Long64_t nEntries = tree->GetEntries();
  for (Long64_t i = 0; i < nEntries; ++i) {
    tree->GetEntry(i);

    if (PID != 1000010030) continue; // Process only tritium tracks

    hEabsTot->Fill(energyDep);
    hSourceEnergy->Fill(SourceEnergy);
    std::cout << "Entry " << i << ": Energy Deposit = " << energyDep
              << ", PID = " << PID
              << ", Source Energy = " << SourceEnergy << std::endl;

    // Perform analysis on energy and position data

  }
    // Create a canvas to draw the histograms
    TCanvas* canvas = new TCanvas("canvas", "Tritium Analysis", 800, 600);
    hEabsTot->SetLineColor(kBlue);
    hEabsTot->GetXaxis()->SetTitle("Energy Deposit (MeV)");
    hEabsTot->GetYaxis()->SetTitle("Counts");
    hEabsTot->SetTitle("Total Absorbed Energy Distribution");
    hEabsTot->Draw();

    TCanvas* canvas2 = new TCanvas("canvas2", "Source Energy Distribution", 800, 600);
    hSourceEnergy->SetLineColor(kRed);
    hSourceEnergy->GetXaxis()->SetTitle("Source Energy (MeV)");
    hSourceEnergy->GetYaxis()->SetTitle("Counts");
    hSourceEnergy->SetTitle("Source Energy Distribution");    
    hSourceEnergy->Draw();


    // Save the histograms to a file


  return 0;
}